const arrayPaises = ["Brasil", "Estados Unidos", "Espanha", "Italia", "Portugal"];
arrayPaises.push("Argentina");
console.log(arrayPaises);
arrayPaises.pop();
console.log(arrayPaises);
arrayPaises.unshift("Chile");
console.log(arrayPaises);   
arrayPaises.shift();
console.log(arrayPaises);
console.log(arrayPaises[arrayPaises.length-1]);
console.log(arrayPaises[1]);
console.log(arrayPaises[2]);